LopezCarlos-Topic0
Carlos2711/startup pull request #1
Opened 2016-10-05 13:32 UTC by Carlos2711

2016-10-05 13:48 UTC, afiorenza requested changes
Just a few comments. Well done!

2016-10-05 13:48 UTC, afiorenza commented on 00-HTML-CSS-basics/CSS/style.css
> +/* --------------------------------------------------------------------------*/
This comment are not needed

2016-10-05 13:48 UTC, afiorenza commented on 00-HTML-CSS-basics/Practica0-2-3/CSS/normalize.css
> +/*! normalize.css v5.0.0 | MIT License | github.com/necolas/normalize.css */
You could have one reset file and use it in several places

2016-10-05 13:48 UTC, afiorenza commented on 00-HTML-CSS-basics/Practica1-2.html
> +        <td>Aguas</td>
Avoid using spanish :p

2016-10-05 13:48 UTC, afiorenza commented on 00-HTML-CSS-basics/Practica1-4.html
> +        <label for="inputFirstname" >First name:</label>
`for` attribute should match with the `id` of the input. Also the label should wrap the input.

2016-10-05 13:48 UTC, afiorenza commented on 00-HTML-CSS-basics/Practica1-4.html
> +          <option value="futball">Futball</option>
Minor: it is football

2016-10-06 12:20 UTC, Carlos2711 commented on 00-HTML-CSS-basics/Practica1-2.html
> +        <td>Aguas</td>
Whit "aguas" i refer to "aguas provinciales" ( the company), its not clear, sorry.

2016-10-06 15:15 UTC, afiorenza approved these changes

2016-10-06 15:18 UTC, merged